name: Build Plugin

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "queue"
      BUILD_64x: "true"
      REALM: "sv"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-6"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-1"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "1"